/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'motor_project' 
 * Target:  'Default' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32l4xx.h"

/* Keil::Compiler&ARM Compiler:I/O:STDOUT&Breakpoint@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
#define RTE_Compiler_IO_STDOUT_BKPT     /* Compiler I/O: STDOUT Breakpoint */
/* Keil::Device:STM32Cube Framework:STM32CubeMX@1.1.0 */
#define RTE_DEVICE_FRAMEWORK_CUBE_MX
/* Keil::Device:STM32Cube HAL:Common@1.13.4 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex@1.13.4 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DMA@1.13.4 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:GPIO@1.13.4 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:PWR@1.13.4 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC@1.13.4 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube HAL:TIM@1.13.4 */
#define RTE_DEVICE_HAL_TIM
/* Keil::Device:Startup@1.3.2 */
#define RTE_DEVICE_STARTUP_STM32L4XX    /* Device Startup for STM32L4 */


#endif /* RTE_COMPONENTS_H */
