/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'motor_project' 
 * Target:  'Target_1' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common@1.13.4 */
#define USE_HAL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
